<?php

namespace Drupal\os2forms_fordelingskomponent\Plugin\WebformHandler;

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\os2forms_fordelingskomponent\Helper\FordelingskomponentHelper;
use Drupal\os2forms_fordelingskomponent\Helper\WebformHelperSF2900;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Fordelingskomponent Webform Handler.
 *
 * @WebformHandler(
 *   id = "os2forms_fordelingskomponent_sf2900",
 *   label = @Translation("Fordelingskomponent (sf2900)"),
 *   category = @Translation("Web services"),
 *   description = @Translation("Sends webform submission to Fordelingskomponenten."),
 *   cardinality = \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_UNLIMITED,
 *   results = \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_IGNORED,
 *   submission = \Drupal\webform\Plugin\WebformHandlerInterface::SUBMISSION_REQUIRED,
 * )
 */
final class WebformHandlerSF2900 extends WebformHandlerBase {
  use StringTranslationTrait;

  public const string ID = 'os2forms_fordelingskomponent_sf2900';

  public const ATTACHMENT_ELEMENT = 'attachment_element';

  /**
   * The webform helper.
   */
  private readonly WebformHelperSF2900 $helper;

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    $instance = parent::create($container, $configuration, $plugin_id, $plugin_definition);
    $instance->helper = $container->get(WebformHelperSF2900::class);

    return $instance;
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    $form[FordelingskomponentHelper::KLE_EMNE] = [
      '#title' => $this->t('KLE-emne'),
      '#type' => 'textfield',
      '#default_value' => $this->configuration[FordelingskomponentHelper::KLE_EMNE],
      '#required' => TRUE,
      '#attributes' => [
        'pattern' => FordelingskomponentHelper::KLE_EMNE_PATTERN,
      ],
      '#description' => $this->t('KLE-emne (format: dd.dd.dd)'),
    ];
    $form[FordelingskomponentHelper::HANDLING_FACET] = [
      '#title' => $this->t('Handling-facet'),
      '#type' => 'textfield',
      '#default_value' => $this->configuration[FordelingskomponentHelper::HANDLING_FACET],
      '#attributes' => [
        'pattern' => FordelingskomponentHelper::HANDLING_FACET_PATTERN,
      ],
    ];

    $availableElements = $this->getAttachmentElements();
    $form[static::ATTACHMENT_ELEMENT] = [
      '#type' => 'select',
      '#title' => $this->t('Element that contains the document to send'),
      '#required' => TRUE,
      '#default_value' => $this->configuration[static::ATTACHMENT_ELEMENT] ?? NULL,
      '#options' => $availableElements,
    ];

    // @todo Change the autogenerated stub
    return parent::buildConfigurationForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function validateConfigurationForm(array &$form, FormStateInterface $form_state) {
    $kleEMne = $form_state->getValue(FordelingskomponentHelper::KLE_EMNE);
    if (!preg_match('/' . FordelingskomponentHelper::KLE_EMNE_PATTERN . '/', $kleEMne)) {
      $form_state->setErrorByName(FordelingskomponentHelper::KLE_EMNE, $this->t('Invalid KLE-emne: %kle_emne.', ['%kle_emne' => $kleEMne]));
    }

    $handling_facet = $form_state->getValue(FordelingskomponentHelper::HANDLING_FACET);
    if (!empty($handling_facet) && !preg_match('/' . FordelingskomponentHelper::HANDLING_FACET_PATTERN . '/', $handling_facet)) {
      $form_state->setErrorByName(FordelingskomponentHelper::HANDLING_FACET,
        $this->t('Invalid Handling-facet: %handling_facet.', ['%handling_facet' => $handling_facet]));
    }

    parent::validateConfigurationForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state);

    $this->configuration[FordelingskomponentHelper::KLE_EMNE] = $form_state->getValue(FordelingskomponentHelper::KLE_EMNE);
    $this->configuration[FordelingskomponentHelper::HANDLING_FACET] = $form_state->getValue(FordelingskomponentHelper::HANDLING_FACET);
    $this->configuration[static::ATTACHMENT_ELEMENT] = $form_state->getValue(static::ATTACHMENT_ELEMENT);

  }

  /**
   * {@inheritdoc}
   */
  public function postSave(WebformSubmissionInterface $webform_submission, $update = TRUE) {
    // Run only when submission is completed.
    if (!$webform_submission->isCompleted()) {
      return;
    }

    $this->helper->createJob($webform_submission, $this->configuration);
  }

  /**
   * {@inheritdoc}
   *
   * @phpstan-return void
   */
  public function postDelete(WebformSubmissionInterface $webform_submission) {
    $this->helper->deleteMessages([$webform_submission]);
  }

  /**
   * {@inheritdoc}
   *
   * @phpstan-return void
   */
  public function postPurge(array $webform_submissions) {
    $this->helper->deleteMessages($webform_submissions);
  }

  /**
   * {@inheritdoc}
   */
  public function getSummary() {
    $kleEmne = $this->configuration[FordelingskomponentHelper::KLE_EMNE];
    $handlingFacet = $this->configuration[FordelingskomponentHelper::HANDLING_FACET];

    $build = [
      'info' => [
        '#prefix' => '<div>',
        '#suffix' => '</div>',
        '#markup' => $this->t('KLE-emne: %kle_emne; Handling-facet: %handling_facet',
          [
            '%kle_emne' => $kleEmne,
            '%handling_facet' => $handlingFacet,
          ]),
      ],
    ];

    if ($kleEmne) {
      $build['routing_info'] = [
        '#prefix' => '<div>',
        '#suffix' => '</div>',
      ]
        + Link::createFromRoute(
          $this->t('Show routing info'),
          'os2forms_fordelingskomponent.routing_info', [
            'webform' => $this->getWebform()->id(),
            'handler' => $this->getHandlerId(),
          ]
        )->toRenderable();
    }

    return $build;
  }

  /**
   * Get attachment elements.
   *
   * @phpstan-return array<string, mixed>
   */
  private function getAttachmentElements(): array {
    $elements = $this->getWebform()->getElementsDecodedAndFlattened();

    $elementTypes = [
      'webform_entity_print_attachment:pdf',
      'os2forms_attachment',
    ];
    $elements = array_filter(
      $elements,
      static function (array $element) use ($elementTypes) {
        return in_array($element['#type'], $elementTypes, TRUE);
      }
    );

    return array_map(static function (array $element) {
      return $element['#title'];
    }, $elements);
  }

}
