# https://taskfile.dev

version: "3"

tasks:
  compose:
    cmds:
      - docker compose {{.TASK_ARGS}} {{.CLI_ARGS}}
    internal: true

  composer:
    desc: Run composer inside docker compose setup, e.g. `task {{.TASK}} -- install`
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm phpfpm composer {{.TASK_ARGS}}

  coding-standards:coding-standards:check:
    desc: Apply and check coding-standards
    cmds:
      - task: composer
        vars:
          TASK_ARGS: coding-standards-apply
      - task: composer
        vars:
          TASK_ARGS: coding-standards-check

  default:
    cmds:
      - task --list
    silent: true
