#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

execute_name=execute

usage() {
  (cat >&2 <<EOF
--------------------------------------------------------------------------------

Example usage:

#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)

# The $execute_name function will be invoked in the root of a Drupal 10 installation.
$execute_name() {
  echo "Executing!"
  echo "module_path: \$module_path"
}

source "\$script_dir/base"

EOF
  )

  exit 1
}

# @see https://stackoverflow.com/a/28776166
if ! (return 0 2>/dev/null); then
  (cat >&2 <<EOF
This script (${BASH_SOURCE[0]}) must be sourced!

EOF
)

  usage
fi

if [[ $(type -t "$execute_name") != function ]]; then
  (cat >&2 <<EOF
Function $execute_name does not exist!
EOF
)

  usage
fi

compose() {
  docker compose "$@"
}

shell() {
  compose exec drupal "$@"
}

composer() {
  shell composer "$@"
}

drush() {
  shell vendor/bin/drush "$@"
}

# Extract the module path from the service.
module_path=$(compose run --rm drupal sh -c 'echo $MODULE_PATH')
module_name=$(basename "$module_path")

# https://www.man7.org/linux/man-pages/man1/trap.1p.html
trap teardown EXIT

setup() {
  compose down --remove-orphans
  compose pull
  compose up --detach --remove-orphans --wait

  composer config minimum-stability dev

  # https://getcomposer.org/doc/03-cli.md#modifying-repositories
  composer config repositories.module '{
    "type": "path",
    "url": "web/modules/contrib/os2forms_fordelingskomponent",
    "options": {
      "symlink": false,
      "versions": {
        "os2forms/os2forms_fordelingskomponent": "1.0-dev"
      }
    }
  }'

  composer require os2forms/os2forms_fordelingskomponent --with-all-dependencies

  # Reset Drupal installation
  compose exec drupal sh -c 'find . -name .ht.sqlite -ls -delete; rm web/sites/default/settings.php' || true
  # Install a minimal Drupal site.
  drush --yes site:install --db-url='sqlite://sites/default/files/.ht.sqlite?module=sqlite' minimal

  # Uncomment this line if you need to debug
  # shell bash

  # Finally, install our module.
  drush --yes pm:install "$module_name"
}

teardown() {
  # Remove EXIT trap
  trap - EXIT

  compose down --remove-orphans
}

setup
execute
teardown
