#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

execute_name=execute

usage() {
  (cat >&2 <<EOF
--------------------------------------------------------------------------------

Example usage:

#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)

# The $execute_name function will be invoked in the root of a Drupal 10 installation.
$execute_name() {
  echo "Executing!"
  echo "module_path: \$module_path"
}

source "\$script_dir/base"

EOF
  )

  exit 1
}

# @see https://stackoverflow.com/a/28776166
if ! (return 0 2>/dev/null); then
  (cat >&2 <<EOF
This script (${BASH_SOURCE[0]}) must be sourced!

EOF
)

  usage
fi

if [[ $(type -t "$execute_name") != function ]]; then
  (cat >&2 <<EOF
Function $execute_name does not exist!
EOF
)

  usage
fi

compose() {
  docker compose "$@"
}

shell() {
  compose exec drupal "$@"
}

composer() {
  shell composer "$@"
}

drush() {
  shell vendor/bin/drush "$@"
}

# Extract the module path from the service.
module_path=$(compose run --rm drupal sh -c 'echo $MODULE_PATH')
module_name=$(basename "$module_path")

# https://www.man7.org/linux/man-pages/man1/trap.1p.html
trap teardown EXIT

setup() {
  compose down --remove-orphans
  compose pull
  compose up --detach --remove-orphans --wait
  # Allow all plugins to run.
  composer --no-plugins config allow-plugins true

  composer config minimum-stability dev

  # --------------------------------------------------------------------------------------------------------------------
  # We need to install dev requirements from our module, so we use
  # wikimedia/composer-merge-plugin to merge our module composer.json into
  # Drupal's.
  #
  # wikimedia/composer-merge-plugin is dead and has some issues
  # https://github.com/wikimedia/composer-merge-plugin/issues/159 »
  # https://github.com/wikimedia/composer-merge-plugin/pull/253
  #
  # Install wikimedia/composer-merge-plugin without any configuration
  composer require wikimedia/composer-merge-plugin --with-all-dependencies
  # Patch to make COMPOSER_IGNORE_PLATFORM_REQS=1 have effect
  shell sh -c 'cd vendor/wikimedia/composer-merge-plugin/ && curl https://patch-diff.githubusercontent.com/raw/wikimedia/composer-merge-plugin/pull/253.diff | patch --strip=1'

  # Configure wikimedia/composer-merge-plugin
  composer --no-plugins config extra.merge-plugin.include "$module_path/composer.json"
  # Use --json to actually set a boolean value (rather that a string value, e.g. "true")
  composer --no-plugins config extra.merge-plugin.merge-extra --json true
  composer --no-plugins config extra.merge-plugin.merge-extra-deep --json true
  composer update
  # Our module and its dev requirements are now installed.
  # --------------------------------------------------------------------------------------------------------------------

  # Reset Drupal installation
  compose exec drupal sh -c 'find . -name .ht.sqlite -ls -delete; rm web/sites/default/settings.php' || true
  # Install a minimal Drupal site.
  drush --yes site:install --db-url='sqlite://sites/default/files/.ht.sqlite?module=sqlite' minimal

  # Uncomment this line if you need to debug
  # shell bash

  # Finally, install our module.
  drush --yes pm:install "$module_name"
}

teardown() {
  # Remove EXIT trap
  trap - EXIT

  compose down --remove-orphans
}

setup
execute
teardown
