<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2012 rel. 2 (x64) (http://www.altova.com) by Simon Holmbo (Netcompany A/S) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:altova="http://www.altova.com/xml-schema-extensions" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SP501">
		<xs:annotation>
			<xs:documentation>Ansoegning om personligt tillaeg</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Myndighed" type="myndighedstype"/>
							<xs:element name="ModtagetDato" type="xs:date"/>
							<xs:element name="KLE" type="kle_personligt_og_helbredstillaeg"/>
							<xs:element name="Dokumenter" minOccurs="0" maxOccurs="30">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Dokumentnavn" type="normalString"/>
										<xs:element name="Dokumenttype" type="dokumenttype">
											<xs:annotation>
												<xs:documentation>- Overslag
													- Faktura
													- Bilag
												</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="AnsoegerOplysninger">
					<xs:complexType>
						<xs:choice>
							<xs:element name="Ansoeger">
								<xs:annotation>
									<xs:documentation>Ved ansoegning med login</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Fornavn" type="normalString"/>
										<xs:element name="Mellemnavn" type="normalString" minOccurs="0"/>
										<xs:element name="Efternavn" type="normalString"/>
										<xs:element name="Personnummer" type="personnummer"/>
										<xs:element name="Telefonnummer" type="telefonnummer" minOccurs="0"/>
										<xs:element name="Email" type="mail" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AnsoegningUdenLogin">
								<xs:annotation>
									<xs:documentation>Ved ansoegning uden login</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Fornavn" type="normalString" minOccurs="0"/>
										<xs:element name="Mellemnavn" type="normalString" minOccurs="0"/>
										<xs:element name="Efternavn" type="normalString" minOccurs="0"/>
										<xs:element name="Personnummer" type="personnummer" minOccurs="0"/>
										<xs:element name="Telefonnummer" type="telefonnummer" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="AnsoegningsOplysninger" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Oplysninger fra ansoenging som samliv, formaal mm.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Civilstand" type="civilstand" minOccurs="0"/>
							<xs:element name="AegtefaelleFornavn" type="normalString" minOccurs="0"/>
							<xs:element name="AegtefaelleMellemnavn" type="normalString" minOccurs="0"/>
							<xs:element name="AegtefaelleEfternavn" type="normalString" minOccurs="0"/>
							<xs:element name="AegtefaellePersonnummer" type="personnummer" minOccurs="0"/>
							<xs:element name="Boform" type="boform" minOccurs="0"/>
							<xs:element name="Formaal" type="normalString" minOccurs="0"/>
							<xs:element name="ForventetUdgiftFormaal" type="beloeb" minOccurs="0"/>
							<xs:element name="BegrundelseAnsoegning" type="longString" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Formueoplysninger" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Oplysninger om borger og evt aegtefaelles formue</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BorgerFormue" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om borgers formue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="IndestaaendePengeinstitut" type="beloeb" minOccurs="0"/>
										<xs:element name="Obligationer" type="beloeb" minOccurs="0"/>
										<xs:element name="Pantebreve" type="beloeb" minOccurs="0"/>
										<xs:element name="Aktier" type="beloeb" minOccurs="0"/>
										<xs:element name="Kontantbeholdning" type="beloeb" minOccurs="0"/>
										<xs:element name="SommerhusFrivaerdi" type="beloeb" minOccurs="0"/>
										<xs:element name="UhaevetKapitalPension" type="beloeb" minOccurs="0"/>
										<xs:element name="AndreVaerdipapirer" type="beloeb" minOccurs="0"/>
										<xs:element name="NedsparingsLaanKreditFastEjendom" type="JaNej" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AegtefaelleFormue" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om aegtefaelle/samlevers formue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="IndestaaendePengeinstitut" type="beloeb" minOccurs="0"/>
										<xs:element name="Obligationer" type="beloeb" minOccurs="0"/>
										<xs:element name="Pantebreve" type="beloeb" minOccurs="0"/>
										<xs:element name="Aktier" type="beloeb" minOccurs="0"/>
										<xs:element name="Kontantbeholdning" type="beloeb" minOccurs="0"/>
										<xs:element name="SommerhusFrivaerdi" type="beloeb" minOccurs="0"/>
										<xs:element name="UhaevetKapitalPension" type="beloeb" minOccurs="0"/>
										<xs:element name="AndreVaerdipapirer" type="beloeb" minOccurs="0"/>
										<xs:element name="NedsparingsLaanKreditFastEjendom" type="JaNej" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="AktuelleIndtaegter" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Oplysninger om borger og evt aegtefaelles indtaegter per maaned</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BorgerIndtaegter" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om borgers indtaegter per maaned</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Loen" type="beloeb" minOccurs="0"/>
										<xs:element name="FolkepensionFoertidspension" type="beloeb" minOccurs="0"/>
										<xs:element name="ATP" type="beloeb" minOccurs="0"/>
										<xs:element name="AndenPension" type="beloeb" minOccurs="0"/>
										<xs:element name="Boligydelse" type="beloeb" minOccurs="0"/>
										<xs:element name="Renteindtaegter" type="beloeb" minOccurs="0"/>
										<xs:element name="Andet1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Andet2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AegtefaelleIndtaegt" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om aegtefaelle/samlevers indtaegter per maaned</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Loen" type="beloeb" minOccurs="0"/>
										<xs:element name="FolkepensionFoertidspension" type="beloeb" minOccurs="0"/>
										<xs:element name="ATP" type="beloeb" minOccurs="0"/>
										<xs:element name="AndenPension" type="beloeb" minOccurs="0"/>
										<xs:element name="Boligydelse" type="beloeb" minOccurs="0"/>
										<xs:element name="Renteindtaegter" type="beloeb" minOccurs="0"/>
										<xs:element name="Andet1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Andet2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="AktuelleUdgifter" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Oplysninger om borger og evt aegtefaelles udgifter per maaned</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="BorgerUdgift" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om borgers udgifter per maaned</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Husleje" type="beloeb" minOccurs="0"/>
										<xs:element name="Terminsudgifter" type="beloeb" minOccurs="0"/>
										<xs:element name="Vandafgift" type="beloeb" minOccurs="0"/>
										<xs:element name="El" type="beloeb" minOccurs="0"/>
										<xs:element name="Varme" type="beloeb" minOccurs="0"/>
										<xs:element name="Forsikring1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Forsikring1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Forsikring1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Forsikring2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Forsikring2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Forsikring2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="SygeforsikringDK" type="beloeb" minOccurs="0"/>
										<xs:element name="TelefonAbonnement" type="beloeb" minOccurs="0"/>
										<xs:element name="Andet1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Andet2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="AegtefaelleUdgift" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Oplysninger om aegtefaelle/samlevers udgifter per maaned</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Husleje" type="beloeb" minOccurs="0"/>
										<xs:element name="Terminsudgifter" type="beloeb" minOccurs="0"/>
										<xs:element name="Vandafgift" type="beloeb" minOccurs="0"/>
										<xs:element name="El" type="beloeb" minOccurs="0"/>
										<xs:element name="Varme" type="beloeb" minOccurs="0"/>
										<xs:element name="Forsikring1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Forsikring1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Forsikring1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Forsikring2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Forsikring2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Forsikring2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>										<xs:element name="SygeforsikringDK" type="beloeb" minOccurs="0"/>
										<xs:element name="TelefonAbonnement" type="beloeb" minOccurs="0"/>
										<xs:element name="Andet1" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet1Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet1Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Andet2" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Andet2Titel" type="normalString" minOccurs="1"/>
													<xs:element name="Andet2Beloeb" type="beloeb" minOccurs="1"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Sygeforsikring" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Medlem af Sygeforsikringen »danmark«</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Gruppe" type="sygesikringstype"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Erklaering" type="accept">
					<xs:annotation>
						<xs:documentation>Kender rettigheder og pligter om behandling af personoplysninger</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Underskriftsoplysninger">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Underskrift"/>
							<xs:element name="Underskriftsdato" type="xs:date"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Fuldmagt" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="FuldmagtDokumentnavn"/>
							<xs:element name="FuldmagthaversPersonnummer" type="personnummer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="personnummer">
		<xs:annotation>
			<xs:documentation>Personnummer</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:length value="22"/>
			<xs:pattern value="urn:oio:cpr:\d+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="telefonnummer">
		<xs:annotation>
			<xs:documentation>Telefonnummer</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="\d+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="accept">
		<xs:annotation>
			<xs:documentation>Tilkendegiver accept</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="Accepteret"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dokumenttype">
		<xs:annotation>
			<xs:documentation>Angiver dokumenttype</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Overslag"/>
			<xs:enumeration value="Faktura"/>
			<xs:enumeration value="Bilag"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="mail">
		<xs:annotation>
			<xs:documentation>E-mail address</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value=".+@.+\..+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="civilstand">
		<xs:annotation>
			<xs:documentation>Angiver civilstand</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Enlig"/>
			<xs:enumeration value="SamlevendeMedAegtefaelle"/>
			<xs:enumeration value="SamlevendeAndenPerson"/>
			<xs:enumeration value="SamlevendeSlaegtning"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="boform">
		<xs:annotation>
			<xs:documentation>Angiver boform</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Lejebolig"/>
			<xs:enumeration value="Andelbolig"/>
			<xs:enumeration value="Ejerbolig"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="beloeb">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2"/>
			<xs:minExclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="normalString">
		<xs:restriction base="xs:string">
			<xs:maxLength value="200"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="longString">
		<xs:restriction base="xs:string">
			<xs:maxLength value="500"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="JaNej" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Ja"/>
			<xs:enumeration value="Nej"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sygesikringstype">
		<xs:annotation>
			<xs:documentation>Angiver sygesikringstype</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="GRUPPE_1"/>
			<xs:enumeration value="GRUPPE_2"/>
			<xs:enumeration value="GRUPPE_5"/>
			<xs:enumeration value="GRUPPE_E"/>
			<xs:enumeration value="GRUPPE_N"/>
			<xs:enumeration value="GRUPPE_S"/>
			<xs:enumeration value="GRUPPE_BASIS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="myndighedstype">
		<xs:annotation>
			<xs:documentation>Myndighedstype</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="urn:oio:cvr-nr:[0-9]{8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="kle_personligt_og_helbredstillaeg">
		<xs:annotation>
			<xs:documentation>KLE format for personligt- og helbredstillæg</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="32.03.12"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
