name: Project

env:
  COMPOSE_USER: root

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  code-analysis:
    name: PHP - Code analysis
    runs-on: ubuntu-latest
    environment:
      BUILDKIT_PROGRESS: plain
    steps:
      - uses: actions/checkout@v5

      # https://github.com/mxschmitt/action-tmate?tab=readme-ov-file#manually-triggered-debug
      # Enable tmate debugging if debug logging is enabled (cf.
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#runner-context)
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
        if: 1 == runner.debug

      - run: |
          ./scripts/code-analysis

  rector:
    name: PHP - Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: |
          ./scripts/rector
