name: Project

env:
  COMPOSE_USER: root
  COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  code-analysis:
    name: PHP - Code analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: |
          ./scripts/code-analysis

  rector:
    name: PHP - Rector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - run: |
          ./scripts/rector
